//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 大專.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;

    public partial class Password
    {
        public int memberID { get; set; }
        [Required(ErrorMessage = "此欄位不能為空")]
        [Display(Name = "目前密碼")]
        public string password { get; set; }
        [Required(ErrorMessage = "此欄位不能為空")]
        [Display(Name = "新的密碼")]
        [StringLength(16, ErrorMessage = "密碼必須8~16個字元", MinimumLength = 8)]
        public string newPassword { get; set; }
        [Required(ErrorMessage = "此欄位不能為空")]
        [Display(Name = "確認密碼")]        
        public string confirmNewPassword { get; set; }
    }
}
